project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - exhibition-datamodel.qmd
    - artist-datamodel.qmd
    - project-log.qmd
    - wikidata.qmd
    - wikidata-item.ipynb
metadata:
  author:
    - name: "Aravind Nagendran"
      orcid: "0009-0006-7095-4020"

website:
  title: "BIM Prototype 02"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: exhibition-datamodel.qmd
        text: Ausstellungs-Datenmodell
      - href: artist-datamodel.qmd
        text: Künstler-Datenmodell
      - href: project-log.qmd
        text: Project Log
      - href: wikidata.qmd
        text: Wikidata
      - href: wikidata-item.ipynb
        text: Item Profile

format:
  html:
    theme: cosmo
    toc: true

execute:
  freeze: auto
